# Variables
CC = gcc
CFLAGS = -Wall -g -c

# Directories
OBJDIR := obj
TGTDIR := target
SRCDIR := src

# Sources list
SRCS := main.c kernel.c

# targets and prerequisites
sources = $(addprefix $(SRCDIR)/,$(SRCS))
objects = $(patsubst %.c,%.o,$(SRCS))
target = main

$(target): $(objects)
	$(CC) -o $(TGTDIR)/$(target) $(OBJDIR)/$(objects)

$(objects): $(sources) folders
	$(CC) $(CFLAGS) $< -o $(OBJDIR)/$@

folders:
	mkdir -p $(OBJDIR)
	mkdir -p $(TGTDIR)

.PHONY: clean
clean:
	rm -rf $(OBJDIR) $(TGTDIR)
